/*
* The MIT License
*
* Copyright (c) 2019 Derick Felix
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
 */
package com.github.derickfelix.bankapplication.views;

public class UsersFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsersFrame
     */
    public UsersFrame()
    {
        initComponents();
        customSettings();
    }
    
    private void customSettings()
    {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        scrollPane = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        toolbar = new javax.swing.JToolBar();
        tbtnSearch = new javax.swing.JButton();
        tbtnAdd = new javax.swing.JButton();
        tbtnEdit = new javax.swing.JButton();
        tbtnDelete = new javax.swing.JButton();
        tbtnExport = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        paneLines = new javax.swing.JPanel();
        lblLine = new javax.swing.JLabel();
        txtLine = new javax.swing.JLabel();
        paneInputs = new javax.swing.JPanel();
        lblCode = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Zwei Bank Application - Users");

        mainTable.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Code", "Name", "Username", "Role"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(mainTable);

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        tbtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        tbtnSearch.setToolTipText("Search");
        tbtnSearch.setFocusable(false);
        tbtnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tbtnSearchActionPerformed(evt);
            }
        });
        toolbar.add(tbtnSearch);

        tbtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        tbtnAdd.setToolTipText("Add New");
        tbtnAdd.setFocusable(false);
        tbtnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tbtnAddActionPerformed(evt);
            }
        });
        toolbar.add(tbtnAdd);

        tbtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        tbtnEdit.setToolTipText("Edit Item");
        tbtnEdit.setFocusable(false);
        tbtnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnEdit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tbtnEditActionPerformed(evt);
            }
        });
        toolbar.add(tbtnEdit);

        tbtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        tbtnDelete.setToolTipText("Delete Item");
        tbtnDelete.setFocusable(false);
        tbtnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tbtnDeleteActionPerformed(evt);
            }
        });
        toolbar.add(tbtnDelete);

        tbtnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        tbtnExport.setToolTipText("Export Data");
        tbtnExport.setFocusable(false);
        tbtnExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnExport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tbtnExportActionPerformed(evt);
            }
        });
        toolbar.add(tbtnExport);

        btnSearch.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        paneLines.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLine.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        lblLine.setText("Line:");

        txtLine.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        txtLine.setText("0/0");

        javax.swing.GroupLayout paneLinesLayout = new javax.swing.GroupLayout(paneLines);
        paneLines.setLayout(paneLinesLayout);
        paneLinesLayout.setHorizontalGroup(
            paneLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLinesLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLine, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneLinesLayout.setVerticalGroup(
            paneLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLinesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(paneLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLine)
                    .addComponent(txtLine))
                .addGap(0, 0, 0))
        );

        paneInputs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        lblCode.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        lblCode.setText("Code");

        txtCode.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N

        lblUsername.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout paneInputsLayout = new javax.swing.GroupLayout(paneInputs);
        paneInputs.setLayout(paneInputsLayout);
        paneInputsLayout.setHorizontalGroup(
            paneInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCode)
                    .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneInputsLayout.setVerticalGroup(
            paneInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(paneInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(paneInputsLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername))
                    .addGroup(paneInputsLayout.createSequentialGroup()
                        .addComponent(lblCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneLines, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSearch))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnSearchActionPerformed
    {//GEN-HEADEREND:event_tbtnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnSearchActionPerformed

    private void tbtnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnAddActionPerformed
    {//GEN-HEADEREND:event_tbtnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnAddActionPerformed

    private void tbtnEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnEditActionPerformed
    {//GEN-HEADEREND:event_tbtnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnEditActionPerformed

    private void tbtnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnDeleteActionPerformed
    {//GEN-HEADEREND:event_tbtnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnDeleteActionPerformed

    private void tbtnExportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnExportActionPerformed
    {//GEN-HEADEREND:event_tbtnExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnExportActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchActionPerformed
    {//GEN-HEADEREND:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable mainTable;
    private javax.swing.JPanel paneInputs;
    private javax.swing.JPanel paneLines;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton tbtnAdd;
    private javax.swing.JButton tbtnDelete;
    private javax.swing.JButton tbtnEdit;
    private javax.swing.JButton tbtnExport;
    private javax.swing.JButton tbtnSearch;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JTextField txtCode;
    private javax.swing.JLabel txtLine;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
