/*
* The MIT License
*
* Copyright (c) 2019 Derick Felix
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
 */
package com.github.derickfelix.bankapplication.views.customers;

import com.github.derickfelix.bankapplication.models.Operation;
import com.github.derickfelix.bankapplication.repositories.OperationRepository;
import com.github.derickfelix.bankapplication.repositories.impl.OperationRepositoryImpl;
import com.github.derickfelix.bankapplication.securities.AuthSecurity;
import com.github.derickfelix.bankapplication.utilities.MessageUtility;
import com.github.derickfelix.bankapplication.utilities.ViewUtility;
import com.github.derickfelix.bankapplication.views.custom.StripedTableCellRenderer;
import com.github.derickfelix.bankapplication.views.dialogs.ExportDialog;
import java.awt.event.KeyEvent;
import java.awt.Font;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

public class AccountInfoFrame extends javax.swing.JInternalFrame {

    private final CustomerMainForm customerMainForm;
    private final OperationRepository operationRepository;
    private final String accountNumber;
    private List<Operation> operations;
    
    public AccountInfoFrame(CustomerMainForm customerMainForm)
    {
        this.customerMainForm = customerMainForm;
        this.operationRepository = OperationRepositoryImpl.getOPInstance();
        this.accountNumber = AuthSecurity.getCustomer().getAccountNumber();

        initComponents();
        customSettings();
    }
    
    private void customSettings()
    {
        DefaultTableCellRenderer leftRenderer = new StripedTableCellRenderer(JLabel.LEFT);
        // Align all to left with stripped color
        mainTable.setDefaultRenderer(String.class, leftRenderer);
        mainTable.getTableHeader().setFont(new Font(Font.DIALOG, Font.PLAIN, 12));
        mainScroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        mainTable.setAutoCreateRowSorter(true);
        
        tbtnExport.setEnabled(false);
        
        defineCurrentBalance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainScroll = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        toolbar = new javax.swing.JToolBar();
        tbtnSearch = new javax.swing.JButton();
        tbtnExport = new javax.swing.JButton();
        separator = new javax.swing.JToolBar.Separator();
        lblCurrentBalance = new javax.swing.JLabel();
        valCurrentBalance = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        lblLine = new javax.swing.JLabel();
        lblSelectedLine = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Zwei Bank Application - Account Information");

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Created At", "Amount", "Operation Type", "Reciever Account"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        mainTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        mainTable.setGridColor(new java.awt.Color(255, 255, 255));
        mainTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mainTable.getTableHeader().setReorderingAllowed(false);
        mainTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                mainTableMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                mainTableMouseClicked(evt);
            }
        });
        mainScroll.setViewportView(mainTable);
        if (mainTable.getColumnModel().getColumnCount() > 0)
        {
            mainTable.getColumnModel().getColumn(0).setMinWidth(150);
            mainTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            mainTable.getColumnModel().getColumn(0).setMaxWidth(200);
            mainTable.getColumnModel().getColumn(1).setMinWidth(150);
            mainTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            mainTable.getColumnModel().getColumn(1).setMaxWidth(200);
            mainTable.getColumnModel().getColumn(2).setMinWidth(150);
            mainTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            mainTable.getColumnModel().getColumn(2).setMaxWidth(200);
            mainTable.getColumnModel().getColumn(3).setMinWidth(200);
            mainTable.getColumnModel().getColumn(3).setPreferredWidth(200);
            mainTable.getColumnModel().getColumn(3).setMaxWidth(250);
        }

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        tbtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        tbtnSearch.setToolTipText("Search");
        tbtnSearch.setFocusable(false);
        tbtnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tbtnSearchActionPerformed(evt);
            }
        });
        toolbar.add(tbtnSearch);

        tbtnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        tbtnExport.setToolTipText("Export Data");
        tbtnExport.setFocusable(false);
        tbtnExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbtnExport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tbtnExportActionPerformed(evt);
            }
        });
        toolbar.add(tbtnExport);
        toolbar.add(separator);

        lblCurrentBalance.setText("Current Balance:  $ ");
        toolbar.add(lblCurrentBalance);

        valCurrentBalance.setText("0.0");
        toolbar.add(valCurrentBalance);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        statusPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblLine.setText("Line:");

        lblSelectedLine.setText("0/0");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelectedLine, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLine)
                    .addComponent(lblSelectedLine))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose))
                    .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSearch))
                .addGap(12, 12, 12))
        );

        setBounds(300, 100, 739, 421);
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnSearchActionPerformed
    {//GEN-HEADEREND:event_tbtnSearchActionPerformed
        search();
    }//GEN-LAST:event_tbtnSearchActionPerformed

    private void tbtnExportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tbtnExportActionPerformed
    {//GEN-HEADEREND:event_tbtnExportActionPerformed
        Enumeration<TableColumn> enumColumns = mainTable.getColumnModel().getColumns();
        List<String> columns = new ArrayList<>();
        
        while (enumColumns.hasMoreElements()) {
            columns.add(enumColumns.nextElement().getHeaderValue().toString());
        }
        
        new ExportDialog(customerMainForm, columns, convertToRows(operations)).setVisible(true);
    }//GEN-LAST:event_tbtnExportActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchActionPerformed
    {//GEN-HEADEREND:event_btnSearchActionPerformed
        search();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void mainTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_mainTableMouseClicked
    {//GEN-HEADEREND:event_mainTableMouseClicked

    }//GEN-LAST:event_mainTableMouseClicked

    private void mainTableMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_mainTableMouseReleased
    {//GEN-HEADEREND:event_mainTableMouseReleased
        lblSelectedLine.setText((mainTable.getSelectedRow() + 1) + "/" + mainTable.getRowCount());
    }//GEN-LAST:event_mainTableMouseReleased

    private void search()
    {
        tbtnExport.setEnabled(false);
        mainScroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        setCursor(ViewUtility.WAIT_CURSOR);
        ViewUtility.clearTable(mainTable);
        operations = operationRepository.findAllByAccountNumber(accountNumber);
        
        if (operations.isEmpty()) {
            MessageUtility.info(customerMainForm, "No results found!");
        } else {
            tbtnExport.setEnabled(true);
            mainScroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        }

        ViewUtility.addRowsToTable(convertToRows(operations), mainTable);
        lblSelectedLine.setText(0 + "/" + mainTable.getRowCount());
        
        setCursor(ViewUtility.DEFAULT_CURSOR);
    }
    
    private void defineCurrentBalance()
    {
        setCursor(ViewUtility.WAIT_CURSOR);
        valCurrentBalance.setText(operationRepository.currentBalance(accountNumber).orElse(0.0).toString());
        setCursor(ViewUtility.DEFAULT_CURSOR);
    }
     
    private List<String[]> convertToRows(List<Operation> operations)
    {
        return operations.stream().map(customer -> {
            String[] row = new String[4];
            row[0] = customer.getCreatedAt().format(DateTimeFormatter.ofPattern("MM/dd/yyyy"));
            row[1] = customer.getAmount() + "";
            row[2] = customer.getType().toString();
            row[3] = customer.getAccountNumber();
            
            return row;
        }).collect(Collectors.toList());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblSelectedLine;
    private javax.swing.JScrollPane mainScroll;
    private javax.swing.JTable mainTable;
    private javax.swing.JToolBar.Separator separator;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JButton tbtnExport;
    private javax.swing.JButton tbtnSearch;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JLabel valCurrentBalance;
    // End of variables declaration//GEN-END:variables
}
